# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Tanken
tagline:             'Developer. Artist.'
description:         'Home of Tanken <a href="https://twitter.com.tanken90/" target="_blank">@tanken90</a>.'
url:                 http://tanken.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ken
  url:               https://twitter.com/tanken90
  email:             kenguashi@gmail.com

# Custom vars
version:             1.0.0
